In [1]:
import numpy as np

a = np.array([0,1,2,3])
print(a)

#Using numpy to create an array of 0 to 9 numbers
print(np.arange(10))


[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
#python lists:

L = range(1000)
%timeit [i**2 for i in L]

#using numpy

a = np.arange(1000)
%timeit a**2

379 µs ± 30.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.59 µs ± 81.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
import numpy as np
a = np.array([0,1,2,3])

#Print dimensions
print(a.ndim)

#shape
print(a.shape)

#Length
print(len(a))


1
(4,)
4


In [13]:
#2D

b = np.array([[0,1,2], [3,4,5]])   #1st list is row and 2nd is col. 

print(b.ndim)
print(b.shape)  #Gives (rows,col)
print(len(b))   #Gives no. of rows


2
(2, 3)
2


In [21]:
#3D array:

c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])     #List within a list. 1st 2d then 3rd dimension.

#1D array is Vector
#2D array is Matrix
#nD array is Tensor

print(c.ndim)
print(c.shape)

3
(2, 2, 2)


Creating Numpy Arrays using Functions

In [30]:
#Using Arrange function

#Arange is an array-valued version of built-in python range func.

a = np.arange(10)      #0.... n-1
print(a)

# Another way is np.arange(start,end,step)

b = np.arange(1, 10, 2)
print(b)

#Using linspace

c = np.linspace(0, 1, 6)  #(start, end, no. of points) #Divides line from start to end into equal parts as step size.
print(c)

#Common arrays: (Uses float datatype)

d = np.ones((3,3))      #Creates all elements with 1's
print(d)

d = np.zeros((4,4))
print(d)

e = np.eye(3)
print(e)

e = np.eye(3, 2)  #(rows,col)
print(e)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.2 0.4 0.6 0.8 1. ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [33]:
#Creating diagonal elemnts:

a = np.diag([1,2,3,4])
print(a)

#Extract diag elements:

print(np.diag(a))


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


In [38]:
#Creating random arrays:

a = np.random.rand(4)   #Array of size 4
#The method rand is from package random and creates uniform random no.
print(a)

#randn creates standard normal no.

b = np.random.randn(3)
print(b)

[0.72998635 0.57838012 0.70831121 0.89063891]
[-0.01052541 -1.64537363  0.56347863]


Datatypes using Numpy:

In [43]:
a = np.arange(10)
print(a.dtype)
print(a)

#Specifying datatype:
a = np.arange(10, dtype='float64')
print(a.dtype)
print(a)

#Can also detect complex, boolean, S6 (String) datatypes also.


int32
[0 1 2 3 4 5 6 7 8 9]
float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [56]:
#Accessing elements:

a = np.arange(10)
print(a[5])

#For multidimensional array

a = np.diag([1,2,3,4])
print(a[2,2])      #Indexes of matrices also start from 0.

#Assingning a value:
a[2,1] = 5
print(a[2,1])

#Slicing:

a = np.arange(10)
print(a[1:8:2])   #(start,end,step)

#Combine Assignment and Slicing:
a[5:] = 10
print(a)

b = np.arange(5)
a[5:] = b[::-1]   #From 5th element insert elements in reverse order.
print(a)

5
3
5
[1 3 5 7]
[ 0  1  2  3  4 10 10 10 10 10]
[0 1 2 3 4 4 3 2 1 0]


Copies and Views:

Slicing creates a view on original array, which is just a way of accessing array data.
Thus, the original array is not copied in memory. Use np.may_share_memory() to check if two arrays share the same memory block.

In [67]:
a = np.arange(10)
print(a)

b = a[::2]
print(b)

print(np.shares_memory(a,b))
#They share the same memory loc because of slicing creates a view which b's element accesses a's element location.
print("Address of a[0] = ",id(a[0]))
print("Address of a[0] = ",id(b[0]))

#If you want to force a copy

c = a[::2].copy()  #copy()
print(c)
print(np.shares_memory(a,c))
print("Address of a[0] = ",id(a[8]))
print("Address of c[0] = ",id(c[4]))

#Still has same address. Doubt: WHY still same address when using copy() but shares_memory shows False? 


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
Address of a[0] =  1786806805992
Address of a[0] =  1786806805992
[0 2 4 6 8]
False
Address of a[0] =  1786806805992
Address of c[0] =  1786806805992


Fancy Indexing:

In [4]:
a = np.random.randint(0, 20, 15)  #(start,end,no.of random numbers)
print(a)

mask = (a % 2 == 0)
extract_from_a = a[mask]
print(extract_from_a)

#Numpy arrays can be indexed with slices but also with boolean or integer arrays (masks). This is called Fancy Indexing.
#It creates copies not views.

print("Address of a[0] = ",id(a[1]))
print("Address of extract[0] = ",id(extract_from_a[0]))
#Still same address dunno why

#Indexing with mask can be used for assignment

a[mask] = -1   #All even positions because of mask above specified will be -1.
print(a)

b = np.arange(0,100,10)
print(b)

b[[4,6]] = -200
print(b)


[18 19  0  4 16 18  4 16  9  5  0 15 16  3  1]
[18  0  4 16 18  4 16  0 16]
Address of a[0] =  1988052452840
Address of extract[0] =  1988052452840
[-1 19 -1 -1 -1 -1 -1 -1  9  5 -1 15 -1  3  1]
[ 0 10 20 30 40 50 60 70 80 90]
[   0   10   20   30 -200   50 -200   70   80   90]


Numerical Operations on Numpy:

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a+1)

b = np.ones(4) + 1
print(a-b)

print(a*b)

#Matrix Multiplication

c = np.diag([1,2,3,4])
print(c*c)
print("**************")
print(c.dot(c))  #Same as normal multiplication

c = np.array([2,5,3,6])
print(a==b)  #Does element wise comparision




[2 3 4 5]
[-1.  0.  1.  2.]
[2. 4. 6. 8.]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
**************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[False  True False False]


In [3]:
#Array-wise comparisions
a = np.array([1,2,3,4])
b = np.array([6,3,1,2])
c = np.array([1,2,3,4])

print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


Logical Operations:

In [19]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

print(np.logical_or(a,b))

[ True  True  True False]


In [21]:
a = np.arange(5)

print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


C:\Users\haxothermic\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


Shape Mismatch: 

In [23]:
#Can't add because both are of different dimensions or sizes

a = np.arange(4)
a + np.arange(3)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Basic Reductions:

In [30]:
x = np.array([1,2,3,4])
print(np.sum(x))

#sum by rows and cols

x = np.array([[1,1], [2,2]])
print(x)

print(x.sum(axis=0))
print(x.sum(axis=1))


print(x.min())
print(x.max())

#index of min element
print(x.argmin())

#index of max element
print(x.argmax())

10
[[1 1]
 [2 2]]
[3 3]
[2 4]
1
2
0
2


Statistics:

In [33]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3], [5,6,1]])
print(x.mean())
print(np.median(x))

print(np.median(y, axis=-1))  #Even -1 means rows

print(x.std())

1.75
1.5
[2. 5.]
0.82915619758885
